### ISSUE TITLE
能不能解释下如何做到数据隐私的问题

### ISSUE THREAD

**Issue by HelloJack0** [SantosFantasyWorld/make-your-own-chatpdf#1]
怎么做到数据保留在本地，然后使用openapi的文本处理功能？

**Comment by SantosFantasyWorld** [comment]
抱歉，如果要使用openai的话，完全的数据隐私没法做到，这个只是相当于利用openai的库来创建一个属于你pdf相关的词库，如果对数据隐私很严格的话，建议不要用这个。
________________________________
From: HelloJack0 ***@***.***>
Sent: Thursday, 1 June 2023 13:19
To: SantosFantasyWorld/make-your-own-chatpdf ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SantosFantasyWorld/make-your-own-chatpdf] 能不能解释下如何做到数据隐私的问题 (Issue #1)


怎么做到数据保留在本地，然后使用openapi的文本处理功能？

―

**Comment by HelloJack0** [comment]
了解了，谢谢
